### ISSUE TITLE
Optimise haptics engine

### ISSUE THREAD

**Issue by yuuiko** [yuuiko/AquaTouch#15]
Currently the AQT Haptics engine fires an applescript variable check for every single haptic. Performance may be improved here.

Idea: Have one script that checks the current haptic setting and sets each haptic trigger via BTTs “update_trigger”. This way haptics won’t check for a variable before firing every time.

**Comment by yuuiko** [comment]
Initial tests show that this idea isn't working.

**Comment by itsnandy** [comment]
v3.5.6 is having issues where haptics is randomly turned on. Tried to turn off but the toggle doesn't behave correctly. Restarting BTT had haptics toggle on and was then able to turn it off.
