### ISSUE TITLE
Sliders can Jump Around (Spotify Sliders Too)

### ISSUE THREAD

**Issue by yuuiko** [yuuiko/AquaTouch#24]
Having some trouble with the spotify sliders jumping around

**Comment by yuuiko** [comment]
Can't seem to reproduce

**Comment by itsnandy** [comment]
Please fix the spacing for the duration slider
<img width="1004" alt="Touch Bar Shot 2020-02-24 at 7 26 17 PM" src="https://user-images.githubusercontent.com/50352448/75203236-9dc76980-573b-11ea-8396-75d21e7c1d34.png">

**Comment by yuuiko** [comment]
@itsnandy what AQT version are you on?

**Comment by itsnandy** [comment]
@yuuiko 3.5.5

**Comment by yuuiko** [comment]
Really? I thought it'd be fixed in that version. See if the upcoming 3.5.6 fixes it.

**Comment by yuuiko** [comment]
Found And Reproduced the issue. 

Sliding the slider conflicts with the slider updating itself, causing a flicker.

**Comment by yuuiko** [comment]
BTT Bug Report seems to have been implemented, sliders now don't update while they are being slided it seems.
