### ISSUE TITLE
MacOS Catalina "Music" support

### ISSUE THREAD

**Issue by yuuiko** [yuuiko/AquaTouch#28]
I have not updated to macOS Catalina, therefore I can't test how AQT behaves with it. 

Could ref GoldenChaos for the music vs iTunes app support. I won't be updating to beta due to important projects.

**Comment by yuuiko** [comment]
- [x] NP widgets
- [x] TouchBar Layout

**Comment by yuuiko** [comment]
fixes have started.

**Comment by yuuiko** [comment]
- Couldn't get album art working
- Difficulty closing the music app

**Comment by Angel-Avila** [comment]
Hi! The first part of the AppleScript doesn't seem to be working for me, the one where it tries to get the artwork. I didn't really test it too much but it seems that it usually enters to the "on error" part, so the script doesn't return anything. I had to take that part out to at least get the artist and song name displayed.

**Comment by yuuiko** [comment]
Which widget is this and could you send the edited script here? (annotations helpful)

**Comment by Angel-Avila** [comment]
It's the Music script in the 'Quick Media' section. The edited script literally just takes out the first `tell current track` command, but [here](https://gist.github.com/Angel-Avila/5949fa7b7bb7d9af83f4f1a134723e3d) you go.

**Comment by yuuiko** [comment]
Ah yes I see it.

Do you have applescript experience? I'm having trouble with the album art in Music widgets and I was wondering if you could help

**Comment by Angel-Avila** [comment]
I do not, but I'll try to see what's going on later & probably tomorrow as well. I'll let you know if I manage to fix it 👍

**Comment by yuuiko** [comment]
Thanks so much! Just disabled the half-broken album art code throughout AQT.

**Comment by Angel-Avila** [comment]
I  tried to get the part of the script that gets the artwork to work but I can't seem to find a solution and haven't seen the question addressed yet. [Here](https://github.com/matryer/bitbar-plugins/issues/1292) is a relevant issue on GitHub and also [here](https://dougscripts.com/itunes/2019/10/yes-there-is-still-an-artwork-issue/) you can find a post about it. 

I think posting those links may give some inside in the future on how to solve the issue of album artwork not showing but for now, the solution to make 'Music' work is disabling the first part of the script that tries to get the artwork raw data, the rest of the script works fine on Catalina.

**Comment by yuuiko** [comment]
Got it working! Ripped apart some stackoverflow read/write code to replace what I had and it ended up working!

<img width="1085" alt="Touch Bar Shot 2020-01-31 at 10 25 42 pm" src="https://user-images.githubusercontent.com/50823728/73535821-a13b3e00-4478-11ea-9438-89ac6641eefc.png">
