### ISSUE TITLE
App Request: Adobe Premiere Pro

### ISSUE THREAD

**Issue by beeb** [yuuiko/AquaTouch#30]
Thanks!

**Comment by yuuiko** [comment]
Hi @beeb!

I just got premiere pro and I'm currently learning it. For now the native touchbar for premiere seems decently good, I was just wondering if you'd like anything to be added into the touchbar as for now the keyboard and current options in the touchbar seem ok so far.

Again though, I just started using premiee so I'm in no way fluent with this program

**Comment by beeb** [comment]
Hey there! I am not currently using AquaTouch so I kinda lost track of what I wanted there. I agree that for now the default touchbar seems okay, lots can be done with keyboard shortcuts too.

Sorry I can't be more helpful right now :/
