### ISSUE TITLE
Chrome YouTube widget looks incomplete, missing play/pause

### ISSUE THREAD

**Issue by beeb** [yuuiko/AquaTouch#31]
Please see screenshot below. I cannot see the play/pause button and the scrollbar doesn't move.

<img width="1085" alt="Touch Bar Shot 2019-08-28 at 18 26 32" src="https://user-images.githubusercontent.com/703631/63874408-c4d9f400-c9c1-11e9-987f-1a3ea855b137.png">

Thanks!

**Comment by yuuiko** [comment]
https://community.folivora.ai/t/1704/584

> Since the script uses Javascript inside AppleScript (which is disabled as a security measure by default), this will not work. To enable this, you have to open Safari's preferences, click the Advanced tab, and enable 'Show Develop menu in menu bar' at the bottom. Once this is done, you have to open the Develop menu and click on 'Allow Javascript from Apple Events' (fourth from the bottom).
> 
> Once all of this is done, the navigation bar will magically start working.

**Comment by beeb** [comment]
I did that on safari but here I'm talking about Chrome. Is there a similar setting?

**Comment by yuuiko** [comment]
Chrome’s youtube shouldn’t show up like that.. Looking into it.

**Comment by yuuiko** [comment]
Does your YouTube Widget group look like this? It seems to be working fine on my side.

<img width="1168" alt="Screen Shot 2019-08-29 at 5 25 52 pm" src="https://user-images.githubusercontent.com/50823728/63919432-18ac1200-ca82-11e9-9c69-602ff8421c47.png">

If not, reinstall AQT and try again. Any version prior to 3.5.2 doesn't have chrome web widgets.

**Comment by beeb** [comment]
Oooh ok by comparing my setup to yours, I had the dropdown on the right to "show app default touch bar" for some reason. I didn't touch anything besides importing the preset but maybe it got messed up on import.
All is good now!

![image](https://user-images.githubusercontent.com/703631/63956117-2bc0e100-ca86-11e9-9d79-a8d3ff7f9cb4.png)

**Comment by yuuiko** [comment]
Yeeeep the mysterious random reset bug strikes again!

Its been a BTT issue for a long time, unfortunately the dev can’t seem to reproduce it so it hasn’t been fixed

Anyhow, glad it works!
