### ISSUE TITLE
Bug: Game Mode doesn't work 

### ISSUE THREAD

**Issue by itsnandy** [yuuiko/AquaTouch#49]
**Describe the bug**
In general, it does not work. As soon as you hit the button, it kicks out BTT and says "You have not yet configured actions in BTT"

**Screenshots**
Please add screenshots to help explain your problem. You can screenshot the touchbar with ⌘⇧6.

**Details:**
 - MacOS Version: LT
 - Current App Version: [e.g. Chrome, Safari, OneNote] LT
 - BTT Version: [e.g. 3.180] LT
 - AQT Version:  LT
 LT -> Latest

**Comment by yuuiko** [comment]
Thank you for the report, It's been neglected so I've been improving it for the next AQT update.
