### ISSUE TITLE
Bug: Finnicky Night Shift

### ISSUE THREAD

**Issue by yuuiko** [yuuiko/AquaTouch#52]
**Describe the bug**
"Minor Bug: When I click on the Night Shift button from the Touchbar, it sometimes randomly goes back to the not night shift mode. Even thought it is being selected in the Touch Bar."

**Comment by itsnandy** [comment]
If I would have Night Shift on manually or set by time and go turn it on from the Touch Bar, it would just keep flashing between Night Shift on and off. It also doesn't show that it's already on.
