### ISSUE TITLE
Bug: True Tone not displaying 

### ISSUE THREAD

**Issue by itsnandy** [yuuiko/AquaTouch#54]
The True Tone toggles work as intended, but it never shows that it is on. It's just a toggle with no feedback whether it's on or not.

**Comment by yuuiko** [comment]
I don't have a TrueTone capable mac and I don't see me being able to get one anytime soon so this one is hard to test.

However, AQT reads the TrueTone state directly from BTT so I'll update the developer to see whether it's implemented properly.
