### ISSUE TITLE
Feature: Setting to Force AQT all the time

### ISSUE THREAD

**Issue by itsnandy** [yuuiko/AquaTouch#57]
At times switching apps, BTT would disappear and would have to use the drop down menu to unhide BTT. Would be great to add some override to force bridgeOS to hide all the time and have BTT be the standard. Thanks!

**Comment by itsnandy** [comment]
I've tried setting the option where global (app-specific settings) is set to show BTT and hide macOS control strip, but for example, if I'm working in Pages and go to Finder then back to Pages, macOS control strip pops up :(

**Comment by yuuiko** [comment]
Hi itsnandy!
Show/Hide behaviour is set on a per-app basis. If you'd like to always show AQT bar, set every app to this:

<img width="1202" alt="Screen Shot 2020-04-09 at 1 54 22 pm" src="https://user-images.githubusercontent.com/50823728/78856313-c5fbf500-7a69-11ea-97d7-da7a68763629.png">

note: manual alterations to AQT don't crossover to new updates

I don't currently see a way to wire this up to the settings, so this may be a feature that I can't implement. I will do some experiments and research but I don't think I can add this to settings.

**Comment by itsnandy** [comment]
Hello @yuuiko! I've tried that setting earlier today and didn't work out, but now it seems to work as intended. I'll try it for the next day or so and I'll let you know how it is. Thanks!
