### ISSUE TITLE
App Request: Visual Studio Code

### ISSUE THREAD

**Issue by edoardop13** [yuuiko/AquaTouch#58]
Button for new file, for comment code, for save file, for connect to repository

**Comment by BleedingDev** [comment]
I would like to help if this is needed to have it sooner! :)

**Comment by BourgonLaurent** [comment]
@httpedo13 @pegak I'm currently working on a VSCode preset, I think it is almost finished, but I'm still unsure about disposition and shortcuts. Also, I use VSCode mainly for Python (and a little of JS). I used the VSCode extensions and Xcode as inspiration (I have been on Xcode almost all day the past few days and the stock integration is quite helpful and intuitive).

Would really love some feedback, so here it is if you want to try it 😄

[vscode-v1.4.zip](https://github.com/yuuiko/AquaTouch/files/5009325/vscode-v1.4.zip)
or
AquaTouch 3.6.1b1, it is included

Notes:
- VSCode must be in English
- The following keyboard shortcuts must be set at default (or set as a secondary shortcut): Trigger IntelliSense, Unindent, Indent, Pause Debug

**Comment by BleedingDev** [comment]
I had to install AT 3.6.1b1 as import of vscode-v1.4 didn't work. I also had to change to Insiders (as I am using it), but now I can finally test it.
Right now I see bot default Mac tabbar and the AT one, even though in other apps I see only AT one.

![image](https://user-images.githubusercontent.com/12586960/89185019-d9dbe180-d599-11ea-82cc-99faf18dbdee.png)

**Comment by BourgonLaurent** [comment]
> Right now I see bot default Mac tabbar and the AT one, even though in other apps I see only AT one.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/12586960/89185019-d9dbe180-d599-11ea-82cc-99faf18dbdee.png)

Ok you have 2 problems:
1. To remove the macOS Control Strip go to `Unsupported apps` inside BTT and make sure `TouchBar Configuration For:` is set to `Show App Default Touch Bar •• Hide Control Strip in case BTT bar is active`. Also check that VSCode Insider is at the same setting.
2. Inside the `Unsupported Apps`, click on `Edit Conditions For Group`. You will then need to add VSCode Insider to the list (you can also just find VSCode and add it), just make sure it is the same name as in the Dock (or you can use the bundle identifier).

**Comment by BleedingDev** [comment]
Thanks, now it shows this way.
![image](https://user-images.githubusercontent.com/12586960/89770324-e5318e80-dafe-11ea-8f84-8b54c3ba0901.png)

**Comment by BourgonLaurent** [comment]
> Thanks, now it shows this way.
> ![image](https://user-images.githubusercontent.com/12586960/89770324-e5318e80-dafe-11ea-8f84-8b54c3ba0901.png)

That's weird... Have you tried AquaTouch 3.6.2? It is now distributed in the stable release, seems like currently some buttons/icons aren't placed correctly (and the DEBUG icon is missing).

**Comment by BourgonLaurent** [comment]
Also, @yuuiko since the application is now in AQT, maybe you could close this issue?

**Comment by anticdimi** [comment]
Hi @yuuiko, is it possible to introduce separate buttons for debugging and running the code (as it is in the default touch bar configuration)?
