### ISSUE TITLE
Bug: Fantastical reverts to "Customize Fantastical Touchbar"

### ISSUE THREAD

**Issue by seishonagon** [yuuiko/AquaTouch#60]
**Describe the bug**
I use fantastical as my main calendar. The AQT settings *ALLWAYS* revert to : 
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/6635078/80907781-f3128f00-8d19-11ea-9003-05ae7cc8c23d.png">
I can set them up, press "Done", but as soon as I shift focus away from Fantastical and come back, I get the "Customize" menu again.
Any idea what I can do to change that behavior?
Thanks!

**Details:**
 - MacOS Version: Catalina 10.15.4
 - Current App Version: Fantastical 3 (3.0.12 (1100.311.08be9e3eda)
 - BTT Version: 3.364
 - AQT Version: 3.5.8

**Comment by yuuiko** [comment]
<img width="1255" alt="Screen Shot 2020-05-04 at 2 23 23 pm" src="https://user-images.githubusercontent.com/50823728/80936103-05242880-8e13-11ea-8026-e3970ae06f9f.png">

**Comment by seishonagon** [comment]
Cool. This seems to solve the issue. Anyway that the "calendar" elements shown in the touchbar open fantastical rather than calendar? It' s my default calendar app ...

Nevermind: It worked by replacing "Calendar.app" by Fantastical in all calls to the widget (Calendar Actions Full Widget etc ...) Although I imagine this will break at the next update?

**Comment by yuuiko** [comment]
Yes you can do that but since its a modification of AQT's main code it'll reset on update

**Comment by yuuiko** [comment]
fantastical Touch Bar has been removed in 3.6
