### ISSUE TITLE
Bug: Spotify Preview is breaking 

### ISSUE THREAD

**Issue by FlowinBeatz** [yuuiko/AquaTouch#66]
**Describe the bug**
I'm very new to AquaTouch so this is from a few hours of using it.

Most of the time the Spotify Preview is not visible. Sometimes it is, then I switch an app and it breaks with only the "Forward" button to be left alone on the left side of the Touch Bar.
Do I click the Forward button, the next songs starts, name and cover of the song is shown for a second than it collapsed again.

**Screenshots**
https://abload.de/img/touchbarbild2020-07-10zkxo.png

**Details:**
 - MacOS Version: 10.15.5
 - Current App Version: -
 - BTT Version: 3.389
 - AQT Version: 3.6

**Comment by yuuiko** [comment]
should be improved for v3.6.8
