### ISSUE TITLE
Bug: Some icons are missing, and clicking ">" doesn't work well

### ISSUE THREAD

**Issue by wao1201** [yuuiko/AquaTouch#77]
**Describe the bug**
After click ">" to activate the AquaTouch bar, there are two icons are missing.
BTW, clicking ">" works only after click some system default touchbar icons. For example, click ">", nothing happened. Click one system dfault touchbr icon (some default actions will work), then click ">" works well (the AquaTouch bar will appear).

**Screenshots**
![IMG_3322](https://user-images.githubusercontent.com/6549984/103168147-a6149780-486b-11eb-8e70-1b42b26d0493.jpg)

**Details:**
 - MacOS Version: Big Sur 11.1 stable version
 - Current App Version: N/A
 - BTT Version: v3.505 (1643)
 - AQT Version: v3.6.4

**Comment by wao1201** [comment]
Update:
even tried restart os, reinstall the AquaTouch, no luck. Still show ? icons like the screenshot and when I long pressed the CMD, Option, and Control key.
Revert to v3.6.3

**Comment by yuuiko** [comment]
This bug was just fixed in v3.6.5!

The unstable macOS Control Strip button is a BTT bug, I can't do much about that one, it would need a BTT bug fix to be fixed
