### ISSUE TITLE
App Request: Microsoft Teams

### ISSUE THREAD

**Issue by AlfredoTinaj** [yuuiko/AquaTouch#78]
Microsoft Teams is used a lot by students also when no pandemic was going on.
Video about what it is and how it works:  [Click to open video on YouTube](https://www.youtube.com/watch?v=OxfukizkyCA)
Video of new update: [Click to open YouTube Video](https://www.youtube.com/watch?v=w_NOLTAzDaQ)

It has a Calendar--> Remiders could be shown on the Touchbar similar to the calendar reminders.
It has Assigments --> They could be split in to-do categories: Today, Tomorrow, This Week
It has Videocalls like Zoom-> Mic(command+shift+m) ,Camera,raise hand, change video Background,share screen etc

![image](https://user-images.githubusercontent.com/50025655/103740012-c88a7b80-4ff6-11eb-9aa8-abe82638f1c9.png)
![image](https://user-images.githubusercontent.com/50025655/103740276-3b93f200-4ff7-11eb-9c5e-996b1f9e6e0e.png)

**Comment by yuuiko** [comment]
Teams does not have any keyboard shortcuts or applescript support I could interface with...
