### ISSUE TITLE
App Request: Notion

### ISSUE THREAD

**Issue by AlfredoTinaj** [yuuiko/AquaTouch#79]
![image](https://user-images.githubusercontent.com/50025655/103740826-47cc7f00-4ff8-11eb-908c-2a499bfe34ac.png)
![image](https://user-images.githubusercontent.com/50025655/103740900-66327a80-4ff8-11eb-8522-845b6b61e7be.png)
![image](https://user-images.githubusercontent.com/50025655/103740867-59ae2200-4ff8-11eb-9e1d-f99b14d27fb1.png)

**Comment by hdoria** [comment]
+1

**Comment by anticdimi** [comment]
+1

**Comment by yuuiko** [comment]
done in 3.6.10
