### ISSUE TITLE
Bug: [Spotify] Song name glitch if artist name contains / \

### ISSUE THREAD

**Issue by sebashb** [yuuiko/AquaTouch#82]
**Describe the bug**
Play this song on Spotify: https://open.spotify.com/track/0RTzJVkunbGwuRjXDFHnjf?si=PTp0vL0iQ4aYwgObcsi1NQ and the song name on the Touch Bar will show a wired JSON see photo bellow. Pretty sure the problem is the forward slash on the Artist name.

**Screenshots**
<img width="1004" alt="Captura da Touch Bar 2021-01-30, às 20 25 54" src="https://user-images.githubusercontent.com/12198921/106367290-5d07a580-6339-11eb-85c8-0768414917bf.png">

**Details:**
 - MacOS Version: macOS 11.1
 - Current App Version: Spotify 1.1.51.380.ga06fdc8d
 - BTT Version: 3.553
 - AQT Version: 3.6.5

**Comment by yuuiko** [comment]
Fixed for AQT v3.7.8
