### ISSUE TITLE
Bug: No scrollbar in Setup Instructions & AquaTouch Guide

### ISSUE THREAD

**Issue by sjackwu** [yuuiko/AquaTouch#85]
**Describe the bug**
There is no scrollbar in Setup instructions (the First Tim Setup page) and AquaTouch Guide (the column on the right-hand side) therefore I could only see the 1st fold of their contents. I can not scroll using 2-fingers or use up/down arrow keys to do so as well.

Could provide links to the 2 documents so that I can at least finish the set up and starting using this amazing tool? :)

**Screenshots**
[First Time Setup](https://www.evernote.com/l/ApoKFllw0ExA-pr8LAnNCuzg0KAJ86CMFPc)
[AquaTouch Guide](https://www.evernote.com/l/Aprh22J9A0BN5KJJrtI_QSMiRou7Ttc0bGA)

**Details:**
 - MacOS Version: 11.4
 - Current App Version: N/A
 - BTT Version: 3.562
 - AQT Version: 3.6.6

**Comment by yuuiko** [comment]
Fixed for 3.6.7.
