### ISSUE TITLE
Bug: BTT crashes after touching "Setup Instructions" during initial setup

### ISSUE THREAD

**Issue by tyadon** [yuuiko/AquaTouch#87]
**Describe the bug**
I just imported and installed the latest version of AquaTouch (3.6.7) and every time I touch "Setup Instructions" a windows opens for a second, then closes, my browser opens to "__bridge_loaded__/", and I get a windows saying that "BetterTouchTool quit unexpectedly" with an accompanying crash report/config info.

**Screenshots**
<img width="1005" alt="Screen Shot 2021-07-16 at 4 24 01 PM" src="https://user-images.githubusercontent.com/3383413/126009920-34509b47-a353-4353-a1bd-58de7d5355f2.png">

**Details:**
 - MacOS Version: Big Sur Version 11.4
 - Current App Version: [e.g. Chrome, Safari, OneNote]
 - BTT Version: Latest Version (3.570)
 - AQT Version: Latest Version (3.6.7)

**Comment by yuuiko** [comment]
should be fixed. awaiting betatest.

**Comment by tyadon** [comment]
Can confirm that it is now working with the beta.
