### ISSUE TITLE
Request: Caps Lock Indicator/Glow

### ISSUE THREAD

**Issue by itsnandy** [yuuiko/AquaTouch#88]
Weird request, but any way to have a caps lock indicator on the Touch Bar? Maybe an always on icon toggle to see if it's on or not. Maybe even have a dim glow instead of an indicator or some background. Thanks much!

**Comment by yuuiko** [comment]
Would probably be possible, but would add another constantly running applescript, reducing efficiency + battery life.

Can see caps lock light in the key anyway!

I'm going to be stricter with features moving forward, prioritising smoothness and stability over features unlike previously.
