### ISSUE TITLE
Bug: constant "update to 3.6.5" notification

### ISSUE THREAD

**Issue by faelin** [yuuiko/AquaTouch#90]
**Describe the bug**
Every time I wake my computer from sleep, I get a notification to update to AQT 3.6.5 via the AQT forum, despite being up to date with the current version.

**Details:**
 - MacOS Version: 12.0.1
 - MacBook Version: MBP 2018, 15-inch
 - BTT Version: 3.624 (build 1774)
 - AQT Version: 3.6.8

**Comment by itsnandy** [comment]
Yup I get constant notifications throughout the day. Looks like dev has taken a break, hope everything is well with them.

**Comment by yuuiko** [comment]
Open BTT Config window
Head to AQT settings in the touchbar and disable update notifications

Might have messed something up last update, so hopefully that setting disables it for now

Yes am on "break" ahah but i am sorting out my macbook and everything to get working soon

**Comment by AndrewBreyen** [comment]
Also having this issue, I disabled notifications just now, hopefully this will temp fix it. 
 If you need logs or anything let us know! 
Thanks for all you do :)

**Comment by yuuiko** [comment]
Fixed in v3.6.9.
